require 'ultimate_points/version.rb'
require 'ultimate_points/config.rb'
require 'ultimate_points/db.rb'
require 'ultimate_points/phpbb.rb'
require 'ultimate_points/map.rb'
require 'ultimate_points/discourse.rb'
